{
 "title": "Project",
 "time": { "from": "2024-03-10T07:49:33.930Z", "to": "2024-03-10T07:56:10.743Z" },
 "panels": [
  {
   "title": "Ambient Light",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Ambient_Light",
     "select": [
      [
       { "params": [ "Ambient_light" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CH4 %",
   "type": "logs",
   "gridPos": { "h": 8, "w": 2, "x": 6, "y": 0 },
   "targets": [
    { "query": "SELECT CH4 FROM CH_4;" }
   ]
  },
  {
   "title": "CO %",
   "type": "logs",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 0 },
   "targets": [
    { "query": "SELECT CO FROM C_O;" }
   ]
  },
  {
   "title": "LPG %",
   "type": "logs",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 0 },
   "targets": [
    { "query": "SELECT LPG FROM L_PG;" }
   ]
  },
  {
   "title": "H2 %",
   "type": "logs",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 0 },
   "targets": [
    { "query": "SELECT H2 FROM H_2;" }
   ]
  },
  {
   "title": "Smoke %",
   "type": "logs",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 0 },
   "targets": [
    { "query": "SELECT Smoke FROM Sm_oke;" }
   ]
  },
  {
   "title": "Propane %",
   "type": "logs",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 0 },
   "targets": [
    { "query": "SELECT Propane FROM Pro_pane;" }
   ]
  },
  {
   "title": "Baby Distance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Baby_Distance",
     "select": [
      [
       { "params": [ "Distance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ambient Sound",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ambient_Sound",
     "select": [
      [
       { "params": [ "Ambient_sound" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "alias": "Gas ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Not_Gas_Conditions",
     "select": [
      [
       { "params": [ "not_ideal_gas_conditions" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Not_Ideal_Env",
     "select": [
      [
       { "params": [ "not_ideal_temp_conditions" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Not_Ideal_Light",
     "select": [
      [
       { "params": [ "not_light_conditions" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Noise",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Not_Ideal_Noise",
     "select": [
      [
       { "params": [ "not_noise_conditions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "query": "SELECT Status FROM Baby_status ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Mean Baby Distance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Baby Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Baby_Distance",
     "select": [
      [
       { "params": [ "Distance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "Heat",
     "measurement": "Baby_Room_Conditions",
     "select": [
      [
       { "params": [ "heat" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "measurement": "Baby_Room_Conditions",
     "select": [
      [
       { "params": [ "hum" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Temperature",
     "measurement": "Baby_Room_Conditions",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}